/**
 * Public heuristic categories, what we optimize, not the proprietary scoring IP.
 * Safe to show customers and answer engines.
 */

export type HeuristicCategory = {
  id: string;
  title: string;
  summary: string;
  examples: string[];
};

/** Dial 1-5: fidelity ↔ savings, with realistic reduction bands. */
export type DialLevel = {
  dial: number;
  name: string;
  summary: string;
  /** Realistic reduction band for typical noisy/mixed work (not a guarantee). */
  expectPercent: string;
};

export const DIAL_LEVELS: DialLevel[] = [
  {
    dial: 1,
    name: "Max Fidelity",
    summary: "Keep nearly everything. Lightest touch, for reviews where every line may matter.",
    expectPercent: "0-10%",
  },
  {
    dial: 2,
    name: "High Fidelity",
    summary: "Trim obvious junk only: clear duplicates, chrome, and pure filler.",
    expectPercent: "5-20%",
  },
  {
    dial: 3,
    name: "Optimized",
    summary: "Balanced default. Collapse low-signal bulk while protecting the ask and unique evidence.",
    expectPercent: "15-45%",
  },
  {
    dial: 4,
    name: "High Savings",
    summary: "Aggressive on noisy logs, multi-file dumps, and repeated frames.",
    expectPercent: "40-70%",
  },
  {
    dial: 5,
    name: "Max Savings",
    summary: "Maximum collapse of low-signal material. Best for fat packs you already trust the profile on.",
    expectPercent: "50-80%",
  },
];

export const HEURISTIC_CATEGORIES: HeuristicCategory[] = [
  {
    id: "repetition",
    title: "Repetition & near-duplicates",
    summary:
      "Identical or near-identical lines, blocks, and frames get collapsed with a count, especially logs and copy-pasted snippets.",
    examples: [
      "Heartbeat / health-check spam",
      "Repeated stack frames",
      "Same paragraph pasted twice",
    ],
  },
  {
    id: "boilerplate",
    title: "Boilerplate & chrome",
    summary:
      "License banners, tool headers, decorative separators, and install fluff that rarely change the answer.",
    examples: [
      "LICENSE / NOTICE blocks",
      "ASCII banners",
      "Generic “generated by” headers",
    ],
  },
  {
    id: "structure",
    title: "Structure over raw bulk",
    summary:
      "Prefer outlines, signatures, and error neighborhoods over entire files when the ask is local.",
    examples: [
      "Function signatures vs full implementations",
      "Error ± context window vs whole log day",
      "Config keys that matter vs every default",
    ],
  },
  {
    id: "profile-bias",
    title: "Profile bias (job-shaped keep lists)",
    summary:
      "Each profile tips what to keep: security-review leans auth and trust edges; log-analysis leans events and anomalies; developer leans code structure.",
    examples: [
      "security-review → auth, secrets, egress",
      "log-analysis → errors, unique events",
      "documentation → headings and claims",
    ],
  },
  {
    id: "dial",
    title: "Dial 1-5 (fidelity ↔ savings)",
    summary:
      "Lower dials keep more original text. Higher dials allow more aggressive collapse of low-signal material. You choose the tradeoff per turn.",
    examples: [
      "Dial 1 · Max Fidelity",
      "Dial 3 · Optimized (default)",
      "Dial 5 · Max Savings",
    ],
  },
  {
    id: "secrets",
    title: "Secret masking (not compression)",
    summary:
      "Credential-shaped patterns are masked on your PC before the model call. Safety, not a savings trick. No scanner is perfect.",
    examples: [
      "API keys",
      "Bearer tokens",
      "Password-like assignments",
    ],
  },
  {
    id: "preserve",
    title: "What we try hard not to “optimize away”",
    summary:
      "Your actual question, unique prose, rare identifiers, and the evidence needed to answer, especially under lower dials.",
    examples: [
      "User ask / constraints",
      "Unique IDs and hostnames you named",
      "One-off error messages",
    ],
  },
];

export const EXPECTATIONS_BLURB =
  "Savings depend on the dial and how noisy the pack is. We are still measuring real workloads; published examples (Noisy ~78%, Security ~60%, Clean ~2%) show the shape of results so far. Clean unique prose often barely moves. Noisy logs, security packs, multi-file dumps, and agent chains are where reduction usually shows up. Proof lives in the dial savings line in the desktop UI per turn.";
